# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('bedroom', models.IntegerField(default=0)),
                ('bathroom', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, max_length=10)),
                ('square_feet', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
