# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:10
from __future__ import unicode_literals

import buy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20170115_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
        migrations.AlterField(
            model_name='buy',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
        migrations.AlterField(
            model_name='buy',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
        migrations.AlterField(
            model_name='buy',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
        migrations.AlterField(
            model_name='buy',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
        migrations.AlterField(
            model_name='buy',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.upload_location),
        ),
    ]
