# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170115_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='\\D?(\\d{0,3}?)\\D{0,2}(\\d{3})?\\D{0,2}(\\d{3})\\D?(\\d{4})$')]),
        ),
    ]
